<?php
$pageTitle = 'Physical copies';
$headerNav = 'staff';
$staffLink = ['href' => '/manage/books', 'label' => 'Books'];
require dirname(__DIR__) . '/partials/layout-top.php';
?>
<p class="eyebrow">Collection management</p><h1>Physical copies</h1>
<?php if ($error): ?><p class="form-error" role="alert"><?= e($error) ?></p><?php endif; ?><?php if ($success): ?><p class="form-success" role="status"><?= e($success) ?></p><?php endif; ?>
<form method="post" class="book-form"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><label for="book_id">Book</label><select id="book_id" name="book_id" required><option value="">Select book</option><?php foreach ($books as $book): ?><option value="<?= e((string) $book['id']) ?>"><?= e($book['title']) ?></option><?php endforeach; ?></select><label for="accession_number">Accession number</label><input id="accession_number" name="accession_number" required maxlength="64"><label for="condition_label">Condition</label><input id="condition_label" name="condition_label" value="good" required maxlength="80"><label for="location">Location</label><input id="location" name="location" required maxlength="120"><button type="submit">Add copy</button></form>
<section class="catalog" aria-labelledby="copy-list"><div class="section-heading"><h2 id="copy-list">Copies</h2><span class="muted"><?= e((string) count($copies)) ?></span></div><?php if ($copies === []): ?><div class="empty-state"><h3>No physical copies yet</h3></div><?php else: ?><div class="book-grid"><?php foreach ($copies as $copy): ?><article class="book-card"><p class="eyebrow"><?= e($copy['status']) ?></p><h3><?= e($copy['title']) ?></h3><p><?= e($copy['accession_number']) ?> · <?= e($copy['location']) ?></p><?php if (!in_array($copy['status'], ['borrowed', 'reserved'], true)): ?><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="status"><input type="hidden" name="id" value="<?= e((string) $copy['id']) ?>"><label for="status-<?= e((string) $copy['id']) ?>">Status</label><select id="status-<?= e((string) $copy['id']) ?>" name="status"><option value="available" <?= $copy['status'] === 'available' ? 'selected' : '' ?>>Available</option><option value="maintenance" <?= $copy['status'] === 'maintenance' ? 'selected' : '' ?>>Maintenance</option><option value="lost" <?= $copy['status'] === 'lost' ? 'selected' : '' ?>>Lost</option><option value="damaged" <?= $copy['status'] === 'damaged' ? 'selected' : '' ?>>Damaged</option></select><button type="submit">Update status</button></form><?php endif; ?></article><?php endforeach; ?></div><?php endif; ?></section>
<?php require dirname(__DIR__) . '/partials/layout-bottom.php'; ?>
