<?php
$pageTitle = 'Books';
$headerNav = 'staff';
require dirname(__DIR__) . '/partials/layout-top.php';
?>
<p class="eyebrow">Collection management</p><h1>Books</h1>
<?php if ($error): ?><p class="form-error" role="alert"><?= e($error) ?></p><?php endif; ?><?php if ($success): ?><p class="form-success" role="status"><?= e($success) ?></p><?php endif; ?>
<form method="post" enctype="multipart/form-data" class="book-form"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><label for="title">Title</label><input id="title" name="title" required maxlength="255"><label for="isbn">ISBN</label><input id="isbn" name="isbn" maxlength="32"><label for="publisher">Publisher</label><input id="publisher" name="publisher" maxlength="180"><label for="publication_year">Publication year</label><input id="publication_year" name="publication_year" type="number" min="1" max="9999"><label for="language">Language</label><input id="language" name="language" value="English" required maxlength="80"><label for="category_id">Category</label><select id="category_id" name="category_id"><option value="">Uncategorized</option><?php foreach ($categories as $category): ?><option value="<?= e((string) $category['id']) ?>"><?= e($category['name']) ?></option><?php endforeach; ?></select><label for="author_ids">Authors</label><select id="author_ids" name="author_ids[]" multiple required><?php foreach ($authors as $author): ?><option value="<?= e((string) $author['id']) ?>"><?= e($author['name']) ?></option><?php endforeach; ?></select><label for="description">Description</label><textarea id="description" name="description" rows="5"></textarea><label for="cover">Cover image</label><input id="cover" name="cover" type="file" accept="image/jpeg,image/png,image/webp"><button type="submit">Add book</button></form>
<section class="catalog" aria-labelledby="book-list"><div class="section-heading"><h2 id="book-list">Books</h2><span class="muted"><?= e((string) count($books)) ?></span></div><?php if ($books === []): ?><div class="empty-state"><h3>No books yet</h3></div><?php else: ?><div class="book-grid"><?php foreach ($books as $book): ?><article class="book-card"><p class="eyebrow"><?= e($book['category'] ?: 'Uncategorized') ?></p><h3><?= e($book['title']) ?></h3><p><?= e((string) $book['copy_count']) ?> copies</p><?php if ($book['status'] === 'active'): ?><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="archive"><input type="hidden" name="id" value="<?= e((string) $book['id']) ?>"><button type="submit">Archive</button></form><?php endif; ?></article><?php endforeach; ?></div><?php endif; ?></section>
<?php require dirname(__DIR__) . '/partials/layout-bottom.php'; ?>
